FROM php:8.1-fpm

WORKDIR /app

RUN docker-php-ext-install mysqli;\
    pecl install xdebug-3.1.3;\
    docker-php-ext-enable xdebug;

ADD ./entrypoint.php.dev.sh /entrypoint.sh

RUN echo '\
opcache.enable=1\n\
opcache.jit=1255\n\
memory_limit=4G\n\
upload_max_filesize=100M\n\
post_max_size=100M\n\
\n\
[Xdebug]\n\
xdebug.mode=debug\n\
xdebug.start_with_request=yes\n\
xdebug.client_port=9003\n\
xdebug.client_host="172.17.0.1"\n' >> /usr/local/etc/php/php.ini

ENTRYPOINT [ "sh", "/entrypoint.sh" ]
CMD [ "php-fpm" ]
